### PR TITLE
add new visual options

### PR DESCRIPTION
**Pull request by Kureii**
**Add new feature**
add option of margin and round coner of background.

### CODE REVIEW

**Comment by nutti** [comment]
@Kureii 

Thanks for the PR! It looks nice feature to me.
I tried your patch in my environment.
But the render result seems not fine.

github_20210407

Could you check your patch in your environment?

**Comment by nutti** [comment]
@Kureii 

Is there any update?
If you stuck, I can help you.

**Comment by Kureii** [comment]
@nutti  
Sorry only I don't have time, too much things to school

**Comment by nutti** [comment]
@Kureii 

No, problem.
If you need a help, feel free to tell me.

**Comment by nutti** [comment]
@Kureii 

Is there any update about this PR?
If you are not enough time to tackle this, I will try to do additional work.

**Comment by Kureii** [comment]
@nutti 
today I finishing my last projecto to the school and now I'll have a time for this

**Comment by Kureii** [comment]
I don't know, where I do mistake, I replace draw_box to draw_roundet_box, but it isint work in draw area mode...

**Comment by nutti** [comment]
@Kureii 

Please double-check your patch while **Background** option is on.
Your patch breaks the background and cursor color.

I will show you the expected behavior

github_20210713

**Comment by nutti** [comment]
@Kureii 

BTW, does this patch work on your environment?
I think that some changes break the layout.

If you provide me the specification of `margin` and `background_round` option, I will fix them.

**Comment by nutti** [comment]
I fixed your patch on my environment.

github_20210715

There are still UI break changes, so we need to fix other places too.

**Comment by nutti** [comment]
@Kureii 

Is it possible to enable **Allow edits by maintainers** of this PR?
I can commit my patch to your branch.

My patch also can be seen from [kureii-patch](https://github.com/nutti/Screencast-Keys/compare/kureii-patch?expand=1) branch.

**Comment by Kureii** [comment]
I had same problem and I didn't know how to repair it

**Comment by nutti** [comment]
@Kureii 

I have already fixed your issue. So I want to merge my codes to your repository.
Could you enable **Allow edits from maintainers** checkbox from right side of this PR?

Please also see this documents.
https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Kureii** [comment]
It's enable

**Comment by nutti** [comment]
@Kureii 

Sorry, I failed the operation.
Could you merge [this branch](https://github.com/nutti/Screencast-Keys/compare/kureii-patch) to master branch and reopen this PR?

**Comment by nutti** [comment]
@Kureii 

Sorry for my failed operation.

I tried to fix the issue.
At first, could you merge this PR?
https://github.com/Kureii/Screencast-Keys/pull/1

**Comment by nutti** [comment]
@Kureii 

Thanks for merging my PR.
I think the current version in master branch on your repository works finet.
Could you check this one on your environment?

**Comment by Kureii** [comment]
It's work good, I don't have any problem

**Comment by nutti** [comment]
@Kureii 

Thanks.
I will merge this PR after some small fix.

**Review by nutti — APPROVED** [review]
LGTM.

Thanks for trying to do this work! @Kureii

**Comment by Kureii** [comment]
I need more practise, this was my first try with coding blender add-on.

**Comment by nutti** [comment]
@Kureii 

Thanks for nice suggestions and great works to this project.
If you consider to contribute to this project more, feel free to open new PR.
This project is contribution welcomed.

**Comment by Kureii** [comment]
thank you for your willingness and patience.

**Pull request merged**
